/*
Copyright (c) 2026, Lars Brubaker
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using MatterHackers.WebGpu.Generator.Model;
using MatterHackers.WebGpu.Generator.Spec;

namespace MatterHackers.WebGpu.Generator.Emit
{
	/// <summary>
	/// Writes the raw binding as C# source. Everything emitted here is 1:1 with the C API - same type
	/// names, same member names, same order - so that a reader can hold webgpu.h beside it. Ergonomics
	/// belong in a separate hand written layer, never in these files.
	/// </summary>
	public sealed class CSharpEmitter
	{
		private const string Namespace = "MatterHackers.WebGpu";
		private const int MaxFileLines = 800;

		private readonly ApiModel model;
		private readonly string outputDirectory;
		private readonly string version;

		public CSharpEmitter(ApiModel model, string outputDirectory, string version)
		{
			this.model = model;
			this.outputDirectory = outputDirectory;
			this.version = version;
		}

		public List<string> WrittenFiles { get; } = new List<string>();

		public void EmitAll()
		{
			Directory.CreateDirectory(this.outputDirectory);
			this.EmitCoreTypes();
			this.EmitEnums();
			this.EmitHandles();
			this.EmitStructs();
			this.EmitFunctions();
			this.EmitStructLayouts();
			this.EmitWasm32StructLayouts();
		}

		private string FileHeader(string summary)
		{
			var builder = new StringBuilder();
			builder.AppendLine("/*");
			builder.AppendLine("Copyright (c) 2026, Lars Brubaker");
			builder.AppendLine("All rights reserved.");
			builder.AppendLine();
			builder.AppendLine("Redistribution and use in source and binary forms, with or without");
			builder.AppendLine("modification, are permitted provided that the following conditions are met:");
			builder.AppendLine();
			builder.AppendLine("1. Redistributions of source code must retain the above copyright notice, this");
			builder.AppendLine("   list of conditions and the following disclaimer.");
			builder.AppendLine("2. Redistributions in binary form must reproduce the above copyright notice,");
			builder.AppendLine("   this list of conditions and the following disclaimer in the documentation");
			builder.AppendLine("   and/or other materials provided with the distribution.");
			builder.AppendLine();
			builder.AppendLine("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND");
			builder.AppendLine("ANY EXPRESS OR IMPLIED WARRANTIES ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT");
			builder.AppendLine("OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DAMAGES ARISING IN ANY WAY OUT OF THE USE");
			builder.AppendLine("OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
			builder.AppendLine("*/");
			builder.AppendLine();
			builder.AppendLine("// <auto-generated>");
			builder.AppendLine($"//     {summary}");
			builder.AppendLine($"//     Generated from wgpu-native {this.version} headers (webgpu.yml / wgpu.h) by");
			builder.AppendLine("//     Submodules/agg-sharp/WebGpu/generator. Do not edit by hand - re-run the");
			builder.AppendLine("//     generator when the pinned wgpu-native version changes.");
			builder.AppendLine("// </auto-generated>");
			builder.AppendLine();
			return builder.ToString();
		}

		private void Write(string fileName, string summary, IEnumerable<string> usings, Action<StringBuilder> body)
		{
			var builder = new StringBuilder();
			builder.Append(this.FileHeader(summary));
			foreach (string @using in usings)
			{
				builder.AppendLine($"using {@using};");
			}

			builder.AppendLine();
			builder.AppendLine($"namespace {Namespace}");
			builder.AppendLine("{");
			body(builder);
			builder.AppendLine("}");

			string path = Path.Combine(this.outputDirectory, fileName);
			string text = builder.ToString().Replace("\r\n", "\n").Replace("\n", Environment.NewLine);
			File.WriteAllText(path, text);
			this.WrittenFiles.Add(path);

			int lines = text.Split('\n').Length;
			if (lines > MaxFileLines)
			{
				Console.WriteLine($"  warning: {fileName} is {lines} lines (limit {MaxFileLines})");
			}
		}

		private void EmitCoreTypes()
		{
			this.Write(
				"CoreTypes.cs",
				"The few webgpu.h types that are declared by hand rather than from the spec, plus its sentinel constants.",
				new[] { "System", "System.Runtime.InteropServices" },
				builder =>
				{
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// webgpu.h's boolean: a 32 bit integer, not the 8 bit value C# would marshal by default.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\t[StructLayout(LayoutKind.Sequential)]");
					builder.AppendLine("\tpublic readonly struct WGPUBool : IEquatable<WGPUBool>");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tprivate readonly uint value;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic WGPUBool(bool value) => this.value = value ? 1u : 0u;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic static implicit operator bool(WGPUBool value) => value.value != 0;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic static implicit operator WGPUBool(bool value) => new WGPUBool(value);");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic bool Equals(WGPUBool other) => (this.value != 0) == (other.value != 0);");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic override bool Equals(object obj) => obj is WGPUBool other && this.Equals(other);");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic override int GetHashCode() => this.value != 0 ? 1 : 0;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic override string ToString() => this.value != 0 ? \"true\" : \"false\";");
					builder.AppendLine("\t}");
					builder.AppendLine();
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// A pointer and length pair. A null <c>data</c> with length <see cref=\"WGPUConstants.WGPU_STRLEN\"/>");
					builder.AppendLine("\t/// means \"no string\"; a non null <c>data</c> with that length means \"null terminated\".");
					builder.AppendLine("\t/// The bytes are UTF-8 and are never owned by this struct.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\t[StructLayout(LayoutKind.Sequential)]");
					builder.AppendLine("\tpublic unsafe struct WGPUStringView");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tpublic byte* data;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic nuint length;");
					builder.AppendLine("\t}");
					builder.AppendLine();
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// The head of an extension chain. Every extension struct starts with one of these, so a");
					builder.AppendLine("\t/// pointer to the extension can be reinterpreted as a pointer to its chain head.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\t[StructLayout(LayoutKind.Sequential)]");
					builder.AppendLine("\tpublic unsafe struct WGPUChainedStruct");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tpublic WGPUChainedStruct* next;");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic WGPUSType sType;");
					builder.AppendLine("\t}");
					builder.AppendLine();
					builder.AppendLine("\t/// <summary>Sentinel values from the WebGPU specification, under their webgpu.h names.</summary>");
					builder.AppendLine("\tpublic static class WGPUConstants");
					builder.AppendLine("\t{");
					bool first = true;
					foreach (var (name, csType, value) in this.model.Constants)
					{
						if (!first)
						{
							builder.AppendLine();
						}

						first = false;

						// nuint cannot be a C# const, so the pointer sized sentinels are static readonly.
						string modifier = csType == "nuint" ? "static readonly" : "const";
						builder.AppendLine($"\t\tpublic {modifier} {csType} {name} = {value};");
					}

					builder.AppendLine("\t}");
				});
		}

		private void EmitEnums()
		{
			var portable = this.model.Enums.Where(e => e.Group == ApiGroup.Portable).OrderBy(e => e.Name, StringComparer.Ordinal).ToList();
			foreach (var chunk in SplitAlphabetically(portable, e => e.Name, 3))
			{
				this.Write(
					$"Enums.{chunk.Label}.cs",
					$"webgpu.h enumerations {chunk.Label.Replace('_', '-')}.",
					new[] { "System" },
					builder => EmitEnumBodies(builder, chunk.Items));
			}

			var native = this.model.Enums.Where(e => e.Group == ApiGroup.Native).ToList();
			this.Write(
				"Enums.Native.cs",
				"wgpu-native's own enumerations from wgpu.h (not part of the portable webgpu.h surface).",
				new[] { "System" },
				builder => EmitEnumBodies(builder, native));
		}

		private static void EmitEnumBodies(StringBuilder builder, IReadOnlyList<EnumDef> enums)
		{
			for (int i = 0; i < enums.Count; i++)
			{
				var enumDef = enums[i];
				if (i > 0)
				{
					builder.AppendLine();
				}

				if (enumDef.IsFlags)
				{
					builder.AppendLine("\t[Flags]");
				}

				builder.AppendLine($"\tpublic enum {enumDef.Name} : {enumDef.Underlying}");
				builder.AppendLine("\t{");
				foreach (var entry in enumDef.Entries)
				{
					string value = enumDef.IsFlags
						? "0x" + entry.Value.ToString("X16", CultureInfo.InvariantCulture)
						: "0x" + entry.Value.ToString("X8", CultureInfo.InvariantCulture);
					// C is happy with WGPUTextureDimension_1D; C# needs a leading letter or underscore.
					string memberName = char.IsDigit(entry.Name[0]) ? "_" + entry.Name : entry.Name;
					builder.AppendLine($"\t\t{memberName} = {value},");
				}

				builder.AppendLine("\t}");
			}
		}

		private void EmitHandles()
		{
			this.Write(
				"Handles.cs",
				"Opaque WebGPU object handles: pointer sized, type safe, and free of any managed lifetime.",
				new[] { "System", "System.Runtime.InteropServices" },
				builder =>
				{
					for (int i = 0; i < this.model.Handles.Count; i++)
					{
						string name = this.model.Handles[i].Name;
						if (i > 0)
						{
							builder.AppendLine();
						}

						builder.AppendLine($"\t/// <summary>An opaque reference to a {name.Substring(4)} owned by the WebGPU implementation.</summary>");
						builder.AppendLine("\t[StructLayout(LayoutKind.Sequential)]");
						builder.AppendLine($"\tpublic readonly struct {name} : IEquatable<{name}>");
						builder.AppendLine("\t{");
						builder.AppendLine("\t\tprivate readonly nint handle;");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic {name}(nint handle) => this.handle = handle;");
						builder.AppendLine();
						builder.AppendLine("\t\tpublic nint Handle => this.handle;");
						builder.AppendLine();
						builder.AppendLine("\t\tpublic bool IsNull => this.handle == 0;");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic bool Equals({name} other) => this.handle == other.handle;");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic override bool Equals(object obj) => obj is {name} other && this.Equals(other);");
						builder.AppendLine();
						builder.AppendLine("\t\tpublic override int GetHashCode() => this.handle.GetHashCode();");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic static bool operator ==({name} left, {name} right) => left.handle == right.handle;");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic static bool operator !=({name} left, {name} right) => left.handle != right.handle;");
						builder.AppendLine();
						builder.AppendLine($"\t\tpublic override string ToString() => \"{name}(0x\" + this.handle.ToString(\"X\") + \")\";");
						builder.AppendLine("\t}");
					}
				});
		}

		// Callback types are deliberately not emitted as managed delegate types. Every callback reaches
		// wgpu either inside a CallbackInfo struct or as a bare parameter, and both spellings are
		// `delegate* unmanaged[Cdecl]` here, which callers fill from an [UnmanagedCallersOnly] method.
		// A [UnmanagedFunctionPointer] delegate would only add a way to hand out a function pointer whose
		// managed target the GC is free to collect.

		private void EmitStructs()
		{
			var portable = this.model.Structs
				.Where(s => s.Group == ApiGroup.Portable && s.Emit)
				.OrderBy(s => s.Name, StringComparer.Ordinal)
				.ToList();
			foreach (var chunk in SplitAlphabetically(portable, s => s.Name, 3))
			{
				this.Write(
					$"Structs.{chunk.Label}.cs",
					$"webgpu.h structures {chunk.Label.Replace('_', '-')}.",
					new[] { "System.Runtime.InteropServices" },
					builder => EmitStructBodies(builder, chunk.Items));
			}

			var native = this.model.Structs.Where(s => s.Group == ApiGroup.Native && s.Emit).ToList();
			this.Write(
				"Structs.Native.cs",
				"wgpu-native's own structures from wgpu.h (not part of the portable webgpu.h surface).",
				new[] { "System.Runtime.InteropServices" },
				builder => EmitStructBodies(builder, native));
		}

		private static void EmitStructBodies(StringBuilder builder, IReadOnlyList<StructDef> structs)
		{
			for (int i = 0; i < structs.Count; i++)
			{
				var structDef = structs[i];
				if (i > 0)
				{
					builder.AppendLine();
				}

				builder.AppendLine(structDef.IsUnion
					? "\t[StructLayout(LayoutKind.Explicit)]"
					: "\t[StructLayout(LayoutKind.Sequential)]");
				builder.AppendLine($"\tpublic unsafe struct {structDef.Name}");
				builder.AppendLine("\t{");
				for (int f = 0; f < structDef.Fields.Count; f++)
				{
					if (f > 0)
					{
						builder.AppendLine();
					}

					if (structDef.IsUnion)
					{
						builder.AppendLine("\t\t[FieldOffset(0)]");
					}

					var field = structDef.Fields[f];
					builder.AppendLine($"\t\tpublic {field.Type.CsType} {Naming.Escape(field.Name)};");
				}

				builder.AppendLine("\t}");
			}
		}

		private void EmitFunctions()
		{
			this.Write(
				"Functions.cs",
				"The portable webgpu.h entry points, exactly as declared in the header.",
				new[] { "System.Runtime.InteropServices" },
				builder =>
				{
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// The raw webgpu.h entry points. Plain <see cref=\"DllImportAttribute\"/> on purpose: the future");
					builder.AppendLine("\t/// emdawnwebgpu (browser) build statically links these symbols and resolves them internally, which");
					builder.AppendLine("\t/// is exactly the shape Emscripten's import model wants. No loader framework, no indirection.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\tpublic static unsafe class Wgpu");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\t/// <summary>The wgpu-native shared library, supplied by the WgpuNative NuGet package.</summary>");
					builder.AppendLine("\t\tpublic const string LibraryName = \"wgpu_native\";");
					EmitFunctionBodies(builder, this.model.Functions.Where(f => f.Group == ApiGroup.Portable).ToList());
					builder.AppendLine("\t}");
				});

			this.Write(
				"Functions.Native.cs",
				"wgpu-native's own entry points from wgpu.h. Calling one is a deliberate step away from browser portability.",
				new[] { "System.Runtime.InteropServices" },
				builder =>
				{
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// Entry points that exist only in wgpu-native (surface configuration extras, logging, adapter");
					builder.AppendLine("\t/// enumeration, device polling). They are kept in their own class so that a browser targeted");
					builder.AppendLine("\t/// build can tell at a glance what it cannot use.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\tpublic static unsafe class WgpuNative");
					builder.AppendLine("\t{");
					EmitFunctionBodies(builder, this.model.Functions.Where(f => f.Group == ApiGroup.Native).ToList());
					builder.AppendLine("\t}");
				});
		}

		private static void EmitFunctionBodies(StringBuilder builder, IReadOnlyList<FunctionDef> functions)
		{
			foreach (var function in functions)
			{
				string parameters = string.Join(", ", function.Parameters.Select(p => $"{p.Type.CsType} {Naming.Escape(p.Name)}"));
				string returns = function.Returns?.CsType ?? "void";
				builder.AppendLine();
				builder.AppendLine($"\t\t[DllImport(Wgpu.LibraryName, CallingConvention = CallingConvention.Cdecl)]");
				builder.AppendLine($"\t\tpublic static extern {returns} {function.Name}({parameters});");
			}
		}

		/// <summary>
		/// Emits the expected C layout of every generated struct, computed here from the member types
		/// declared in the spec. The binding tests assert the C# sizes against this table, which is what
		/// catches a marshalling mistake at test time rather than as memory corruption at run time.
		/// </summary>
		private void EmitStructLayouts()
		{
			var structs = this.model.Structs.OrderBy(s => s.Name, StringComparer.Ordinal).ToList();
			this.Write(
				"StructLayouts.cs",
				"Expected C sizes and alignments for every generated struct, for the layout tests.",
				new[] { "System" },
				builder =>
				{
					builder.AppendLine("\t/// <summary>The C size and alignment a generated struct must have on our 64 bit targets.</summary>");
					builder.AppendLine("\tpublic readonly struct WGPUStructLayout");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tpublic WGPUStructLayout(string name, Type type, int size, int alignment)");
					builder.AppendLine("\t\t{");
					builder.AppendLine("\t\t\tthis.Name = name;");
					builder.AppendLine("\t\t\tthis.Type = type;");
					builder.AppendLine("\t\t\tthis.Size = size;");
					builder.AppendLine("\t\t\tthis.Alignment = alignment;");
					builder.AppendLine("\t\t}");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic string Name { get; }");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic Type Type { get; }");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic int Size { get; }");
					builder.AppendLine();
					builder.AppendLine("\t\tpublic int Alignment { get; }");
					builder.AppendLine("\t}");
					builder.AppendLine();
					builder.AppendLine("\t/// <summary>Every struct in the binding, with the layout the C header gives it.</summary>");
					builder.AppendLine("\tpublic static class WGPUStructLayouts");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tpublic static readonly WGPUStructLayout[] All = new WGPUStructLayout[]");
					builder.AppendLine("\t\t{");
					foreach (var structDef in structs)
					{
						var (size, align) = this.model.LayoutOf(structDef);
						builder.AppendLine($"\t\t\tnew WGPUStructLayout(\"{structDef.Name}\", typeof({structDef.Name}), {size}, {align}),");
					}

					builder.AppendLine("\t\t};");
					builder.AppendLine("\t}");
				});
		}

		/// <summary>
		/// Emits the same table computed for wasm32 - pointers and <c>size_t</c> four bytes wide instead of
		/// eight - plus a self-check that measures the running binding against it.
		/// <para>
		/// This exists because the browser cannot be told it got a struct layout wrong. wgpu-native
		/// validates the descriptors it is handed; emdawnwebgpu reads fields straight out of wasm memory at
		/// hard-coded offsets and passes whatever it finds to the WebGPU IDL, so a size mistake shows up as
		/// a nonsense value in an unrelated field, several calls later. The check is generated with the
		/// table rather than written by hand for the obvious reason: 130-odd numbers nobody could keep
		/// current is worse than no table at all.
		/// </para>
		/// </summary>
		private void EmitWasm32StructLayouts()
		{
			var structs = this.model.Structs.OrderBy(s => s.Name, StringComparer.Ordinal).ToList();

			// The desktop table has already been emitted, so the model is free to be re-measured; put it
			// back afterwards so nothing downstream inherits a wasm32 model.
			this.model.SetPointerWidth(4);
			var layouts = structs.Select(s => (s.Name, Layout: this.model.LayoutOf(s))).ToList();
			this.model.SetPointerWidth(8);

			this.Write(
				"StructLayouts.Wasm32.cs",
				"Expected C sizes and alignments for every generated struct on wasm32, and the boot self-check.",
				new[] { "System", "System.Collections.Generic", "System.Runtime.CompilerServices" },
				builder =>
				{
					builder.AppendLine("\t/// <summary>");
					builder.AppendLine("\t/// The layout every generated struct has when the binding is compiled for wasm32, where a");
					builder.AppendLine("\t/// pointer and a size_t are four bytes rather than eight. Nothing else about C layout differs");
					builder.AppendLine("\t/// from the 64 bit targets, so this table and <see cref=\"WGPUStructLayouts\"/> are the same");
					builder.AppendLine("\t/// computation run at two pointer widths.");
					builder.AppendLine("\t/// </summary>");
					builder.AppendLine("\tpublic static class WGPUStructLayoutsWasm32");
					builder.AppendLine("\t{");
					builder.AppendLine("\t\tpublic static readonly WGPUStructLayout[] All = new WGPUStructLayout[]");
					builder.AppendLine("\t\t{");
					foreach (var (name, layout) in layouts)
					{
						builder.AppendLine($"\t\t\tnew WGPUStructLayout(\"{name}\", typeof({name}), {layout.Size}, {layout.Align}),");
					}

					builder.AppendLine("\t\t};");
					builder.AppendLine();
					builder.AppendLine("\t\t/// <summary>");
					builder.AppendLine("\t\t/// Measures every generated struct against the wasm32 C layout and describes whatever");
					builder.AppendLine("\t\t/// disagrees, or returns null when everything matches. A browser host calls this once at");
					builder.AppendLine("\t\t/// device bring-up: a wrong layout there is silent memory misreading, not a validation error.");
					builder.AppendLine("\t\t/// </summary>");
					builder.AppendLine("\t\t/// <remarks>");
					builder.AppendLine("\t\t/// Every size below is a compile-time <c>Unsafe.SizeOf&lt;T&gt;</c> rather than a reflected");
					builder.AppendLine("\t\t/// <c>Marshal.SizeOf</c>, so this survives trimming and names every struct in a way a rename");
					builder.AppendLine("\t\t/// would break at build time. Alignment is not checked: it is not observable without");
					builder.AppendLine("\t\t/// constructing a probe type per struct, and a wrong alignment moves a size with it.");
					builder.AppendLine("\t\t/// </remarks>");
					builder.AppendLine("\t\t/// <returns>A description of the mismatches, or null when the layout is correct.</returns>");
					builder.AppendLine("\t\tpublic static string DescribeSizeMismatches()");
					builder.AppendLine("\t\t{");
					builder.AppendLine("\t\t\tif (IntPtr.Size != 4)");
					builder.AppendLine("\t\t\t{");
					builder.AppendLine("\t\t\t\t// This table describes wasm32 only. On a 64 bit target WGPUStructLayouts is the one");
					builder.AppendLine("\t\t\t\t// that applies, and the binding tests assert it.");
					builder.AppendLine("\t\t\t\treturn null;");
					builder.AppendLine("\t\t\t}");
					builder.AppendLine();
					builder.AppendLine("\t\t\tvar mismatches = new List<string>();");
					foreach (var (name, layout) in layouts)
					{
						builder.AppendLine($"\t\t\tCheck(mismatches, \"{name}\", Unsafe.SizeOf<{name}>(), {layout.Size});");
					}

					builder.AppendLine();
					builder.AppendLine("\t\t\treturn mismatches.Count == 0 ? null : string.Join(\"; \", mismatches);");
					builder.AppendLine("\t\t}");
					builder.AppendLine();
					builder.AppendLine("\t\tprivate static void Check(List<string> mismatches, string name, int actual, int expected)");
					builder.AppendLine("\t\t{");
					builder.AppendLine("\t\t\tif (actual != expected)");
					builder.AppendLine("\t\t\t{");
					builder.AppendLine("\t\t\t\tmismatches.Add($\"{name}: this build says {actual} bytes, wasm32 C says {expected}\");");
					builder.AppendLine("\t\t\t}");
					builder.AppendLine("\t\t}");
					builder.AppendLine("\t}");
				});
		}

		private readonly struct Chunk<T>
		{
			public Chunk(string label, List<T> items)
			{
				this.Label = label;
				this.Items = items;
			}

			public string Label { get; }

			public List<T> Items { get; }
		}

		/// <summary>
		/// Splits an alphabetically ordered set into roughly equal groups and labels each with the letter
		/// range it covers - so generated files stay under the file size limit while still being findable
		/// by name rather than by an arbitrary number.
		/// </summary>
		private static List<Chunk<T>> SplitAlphabetically<T>(List<T> items, Func<T, string> nameOf, int groups)
		{
			var chunks = new List<Chunk<T>>();
			int perGroup = (items.Count + groups - 1) / groups;
			int start = 0;
			while (start < items.Count)
			{
				int count = Math.Min(perGroup, items.Count - start);

				// Never cut in the middle of a letter: a name's first letter must decide its file.
				while (start + count < items.Count
					&& LetterOf(nameOf(items[start + count - 1])) == LetterOf(nameOf(items[start + count])))
				{
					count++;
				}

				var slice = items.GetRange(start, count);
				char first = LetterOf(nameOf(slice[0]));
				char last = LetterOf(nameOf(slice[slice.Count - 1]));
				chunks.Add(new Chunk<T>(first == last ? first.ToString() : $"{first}_{last}", slice));
				start += count;
			}

			return chunks;
		}

		/// <summary>The first letter after the WGPU prefix, which is what the file labels are keyed on.</summary>
		private static char LetterOf(string name) => name.StartsWith("WGPU", StringComparison.Ordinal) ? name[4] : name[0];
	}
}
