// <auto-generated>
// Hack to disable analyzers and their warnings - too many issues to address
// </auto-generated>
//----------------------------------------------------------------------------
// Anti-Grain Geometry - Version 2.4
// Copyright (C) 2002-2005 Maxim Shemanarev (http://www.antigrain.com)
//
// C# port by: Lars Brubaker
//                  larsbrubaker@gmail.com
// Copyright (C) 2007
//
// Permission to copy, use, modify, sell and distribute this software
// is granted provided this copyright notice appears in all copies.
// This software is provided "as is" without express or implied
// warranty, and with no claim as to its suitability for any purpose.
//
//----------------------------------------------------------------------------
// Contact: mcseem@antigrain.com
//          mcseemagg@yahoo.com
//          http://www.antigrain.com
//----------------------------------------------------------------------------
//
// The Stack Blur Algorithm was invented by Mario Klingemann,
// mario@quasimondo.com and described here:
// http://incubator.quasimondo.com/processing/fast_blur_deluxe.php
// (search phrase "Stackblur: Fast But Good looking").
// The major improvement is that there's no more division table
// that was very expensive to create for large blur radii. Instead,
// for 8-bit per channel and radius not exceeding 254 the division is
// replaced by multiplication and shift.
//
//----------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MatterHackers.Agg.Image
{
	public struct RGBA_Ints
	{
		public int r;
		public int g;
		public int b;
		public int a;
	};

	internal struct stack_blur_tables
	{
		public static ushort[] g_stack_blur8_mul =
        {
            512,512,456,512,328,456,335,512,405,328,271,456,388,335,292,512,
            454,405,364,328,298,271,496,456,420,388,360,335,312,292,273,512,
            482,454,428,405,383,364,345,328,312,298,284,271,259,496,475,456,
            437,420,404,388,374,360,347,335,323,312,302,292,282,273,265,512,
            497,482,468,454,441,428,417,405,394,383,373,364,354,345,337,328,
            320,312,305,298,291,284,278,271,265,259,507,496,485,475,465,456,
            446,437,428,420,412,404,396,388,381,374,367,360,354,347,341,335,
            329,323,318,312,307,302,297,292,287,282,278,273,269,265,261,512,
            505,497,489,482,475,468,461,454,447,441,435,428,422,417,411,405,
            399,394,389,383,378,373,368,364,359,354,350,345,341,337,332,328,
            324,320,316,312,309,305,301,298,294,291,287,284,281,278,274,271,
            268,265,262,259,257,507,501,496,491,485,480,475,470,465,460,456,
            451,446,442,437,433,428,424,420,416,412,408,404,400,396,392,388,
            385,381,377,374,370,367,363,360,357,354,350,347,344,341,338,335,
            332,329,326,323,320,318,315,312,310,307,304,302,299,297,294,292,
            289,287,285,282,280,278,275,273,271,269,267,265,263,261,259
        };

		public static byte[] g_stack_blur8_shr =
        {
              9, 11, 12, 13, 13, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17,
             17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19,
             19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20,
             20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21,
             21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
             21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22,
             22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
             22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
             23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
             23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
             23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
             23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
             24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
             24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
             24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
             24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24
        };
	};

	//==============================================================stack_blur
	/// <summary>
	/// C++ AGG's <c>stack_blur</c>: Mario Klingemann's stack blur, a close approximation of a Gaussian
	/// that costs the same at any radius. Sums are divided by the (radius + 1)^2 weight with the 8-bit
	/// multiply-and-shift tables for radii under 255, truncating as C++ does.
	/// </summary>
	public class stack_blur
	{
		private Color[] buffer = new Color[0];

		private Color[] stack = new Color[0];

		/// <summary>
		/// Whether alpha is blurred with the colour (C++ <c>stack_blur_calc_rgba</c>). Off, it is
		/// <c>stack_blur_calc_rgb</c>: each pixel keeps its own alpha.
		/// </summary>
		public bool BlurAlpha { get; set; }

		/// <summary>
		/// The multiply and shift that stand in for dividing by (radius + 1)^2; (0, 0) from 255 up, where the sums
		/// are divided. The GPU's stack blur takes these so its bytes match.
		/// </summary>
		public static (int Mul, int Shr) DivisionTable(int radius)
		{
			return radius > 0 && radius < 255 ? (stack_blur_tables.g_stack_blur8_mul[radius], stack_blur_tables.g_stack_blur8_shr[radius]) : (0, 0);
		}

		/// <summary>Blurs each row of <paramref name="img"/> by <paramref name="radius"/> pixels; below 1 does nothing.</summary>
		public void blur_x(IImageByte img, int radius)
		{
			if (radius < 1)
			{
				return;
			}

			int w = img.Width;
			int h = img.Height;
			int wm = w - 1;
			int div = radius * 2 + 1;

			int divSum = (radius + 1) * (radius + 1);
			int mulSum = 0;
			int shrSum = 0;
			if (radius < 255)
			{
				mulSum = stack_blur_tables.g_stack_blur8_mul[radius];
				shrSum = stack_blur_tables.g_stack_blur8_shr[radius];
			}

			if (this.buffer.Length < w)
			{
				this.buffer = new Color[w];
			}

			if (this.stack.Length < div)
			{
				this.stack = new Color[div];
			}

			for (int y = 0; y < h; y++)
			{
				var sum = default(RGBA_Ints);
				var sumIn = default(RGBA_Ints);
				var sumOut = default(RGBA_Ints);

				Color pix = img.GetPixel(0, y);
				for (int i = 0; i <= radius; i++)
				{
					this.stack[i] = pix;
					Add(ref sum, pix, i + 1);
					Add(ref sumOut, pix, 1);
				}

				for (int i = 1; i <= radius; i++)
				{
					pix = img.GetPixel((i > wm) ? wm : i, y);
					this.stack[i + radius] = pix;
					Add(ref sum, pix, radius + 1 - i);
					Add(ref sumIn, pix, 1);
				}

				int stackPtr = radius;
				for (int x = 0; x < w; x++)
				{
					// The rgb calculator writes only r, g and b, so the alpha that goes back is the pixel's own.
					Color result = this.BlurAlpha ? default : img.GetPixel(x, y);
					result.red = CalcPix(sum.r, mulSum, shrSum, divSum);
					result.green = CalcPix(sum.g, mulSum, shrSum, divSum);
					result.blue = CalcPix(sum.b, mulSum, shrSum, divSum);
					if (this.BlurAlpha)
					{
						result.alpha = CalcPix(sum.a, mulSum, shrSum, divSum);
					}

					this.buffer[x] = result;

					Sub(ref sum, sumOut);

					int stackStart = stackPtr + div - radius;
					if (stackStart >= div)
					{
						stackStart -= div;
					}

					Add(ref sumOut, this.stack[stackStart], -1);

					int xp = x + radius + 1;
					if (xp > wm)
					{
						xp = wm;
					}

					pix = img.GetPixel(xp, y);
					this.stack[stackStart] = pix;

					Add(ref sumIn, pix, 1);
					Add(ref sum, sumIn);

					++stackPtr;
					if (stackPtr >= div)
					{
						stackPtr = 0;
					}

					Add(ref sumOut, this.stack[stackPtr], 1);
					Add(ref sumIn, this.stack[stackPtr], -1);
				}

				img.copy_color_hspan(0, y, w, this.buffer, 0);
			}
		}

		/// <summary>Blurs each column of <paramref name="img"/> by <paramref name="radius"/> pixels.</summary>
		public void blur_y(IImageByte img, int radius)
		{
			FormatTransposer img2 = new FormatTransposer(img);
			blur_x(img2, radius);
		}

		/// <summary>Blurs <paramref name="img"/> by <paramref name="radius"/> pixels in both directions.</summary>
		public void blur(IImageByte img, int radius)
		{
			blur_x(img, radius);
			FormatTransposer img2 = new FormatTransposer(img);
			blur_x(img2, radius);
		}

		/// <summary>Blurs <paramref name="img"/> by <paramref name="rx"/> across and <paramref name="ry"/> down.</summary>
		public void Blur(ImageBuffer img, int rx, int ry)
		{
			blur_x(img, rx);
			blur_y(img, ry);
		}

		/// <summary>
		/// C++ AGG's <c>stack_blur_gray8</c>: the stack blur of an image of one byte per pixel (a gray image, or one
		/// channel of a colour image seen through a gray view), <paramref name="rx"/> across then <paramref name="ry"/>
		/// down. Radii are capped at 254, where the multiply-and-shift tables end; 0 skips that direction.
		/// </summary>
		public static void BlurGray8(IImageByte img, int rx, int ry)
		{
			byte[] buffer = img.GetBuffer();
			int w = img.Width;
			int h = img.Height;

			// One pass along a line of `length` bytes: `offsetAt(i)` is the i'th byte of the line.
			void BlurLine(Func<int, int> offsetAt, int length, int radius, int[] stack, int mul, int shr)
			{
				int div = radius * 2 + 1;
				int last = length - 1;
				int sum = 0;
				int sumIn = 0;
				int sumOut = 0;

				int pix = buffer[offsetAt(0)];
				for (int i = 0; i <= radius; i++)
				{
					stack[i] = pix;
					sum += pix * (i + 1);
					sumOut += pix;
				}

				for (int i = 1; i <= radius; i++)
				{
					pix = buffer[offsetAt(Math.Min(i, last))];
					stack[i + radius] = pix;
					sum += pix * (radius + 1 - i);
					sumIn += pix;
				}

				int stackPtr = radius;
				int read = Math.Min(radius, last);
				for (int i = 0; i < length; i++)
				{
					// C++ keeps the sums unsigned: the product needs all 32 bits at large radii.
					buffer[offsetAt(i)] = (byte)(((uint)sum * (uint)mul) >> shr);

					sum -= sumOut;

					int stackStart = stackPtr + div - radius;
					if (stackStart >= div)
					{
						stackStart -= div;
					}

					sumOut -= stack[stackStart];

					// Past the end the last pixel read is repeated.
					if (read < last)
					{
						pix = buffer[offsetAt(++read)];
					}

					stack[stackStart] = pix;

					sumIn += pix;
					sum += sumIn;

					++stackPtr;
					if (stackPtr >= div)
					{
						stackPtr = 0;
					}

					sumOut += stack[stackPtr];
					sumIn -= stack[stackPtr];
				}
			}

			if (rx > 0)
			{
				rx = Math.Min(rx, 254);
				var stack = new int[rx * 2 + 1];
				for (int y = 0; y < h; y++)
				{
					BlurLine(x => img.GetBufferOffsetXY(x, y), w, rx, stack, stack_blur_tables.g_stack_blur8_mul[rx], stack_blur_tables.g_stack_blur8_shr[rx]);
				}
			}

			if (ry > 0)
			{
				ry = Math.Min(ry, 254);
				var stack = new int[ry * 2 + 1];
				for (int x = 0; x < w; x++)
				{
					BlurLine(y => img.GetBufferOffsetXY(x, y), h, ry, stack, stack_blur_tables.g_stack_blur8_mul[ry], stack_blur_tables.g_stack_blur8_shr[ry]);
				}
			}
		}

		// The tables' multiply falls just short of 2^shr / div, but never far enough to drop a flat field
		// (StackBlurTests). The product needs all 32 bits at large radii, so it is unsigned, as in C++.
		private static byte CalcPix(int sum, int mul, int shr, int div)
		{
			return (byte)(mul != 0 ? ((uint)sum * (uint)mul) >> shr : (uint)(sum / div));
		}

		private static void Add(ref RGBA_Ints sum, Color c, int k)
		{
			sum.r += c.red * k;
			sum.g += c.green * k;
			sum.b += c.blue * k;
			sum.a += c.alpha * k;
		}

		private static void Add(ref RGBA_Ints sum, RGBA_Ints v)
		{
			sum.r += v.r;
			sum.g += v.g;
			sum.b += v.b;
			sum.a += v.a;
		}

		private static void Sub(ref RGBA_Ints sum, RGBA_Ints v)
		{
			sum.r -= v.r;
			sum.g -= v.g;
			sum.b -= v.b;
			sum.a -= v.a;
		}
	}

	public abstract class RecursizeBlurCalculator
	{
		public double r, g, b, a;

		public abstract RecursizeBlurCalculator CreateNew();

		public abstract void from_pix(Color c);

		public abstract void calc(double b1, double b2, double b3, double b4,
			RecursizeBlurCalculator c1, RecursizeBlurCalculator c2, RecursizeBlurCalculator c3, RecursizeBlurCalculator c4);

		public abstract void to_pix(ref Color c);

		/// <summary>
		/// A blurred channel back to a byte: rounded, and clamped because the filter can ring a little past
		/// 0 or 255, where a bare cast would wrap. (C++ AGG 2.6 truncates, turning a white area 253 after both
		/// passes; the reference renderer's patches/agg_blur.h rounds and clamps as here.)
		/// </summary>
		protected static byte ToByte(double value)
		{
			return value <= 0 ? (byte)0 : value >= 255 ? (byte)255 : (byte)Util.uround(value);
		}
	};

	//===========================================================recursive_blur
	public sealed class RecursiveBlur
	{
		private List<RecursizeBlurCalculator> m_sum1;
		private List<RecursizeBlurCalculator> m_sum2;
		private VectorPOD<Color> m_buf;
		private RecursizeBlurCalculator m_RecursizeBlurCalculatorFactory;

		public RecursiveBlur(RecursizeBlurCalculator recursizeBluerCalculatorFactory)
		{
			m_sum1 = new List<RecursizeBlurCalculator>();
			m_sum2 = new List<RecursizeBlurCalculator>();
			m_buf = new VectorPOD<Color>();
			m_RecursizeBlurCalculatorFactory = recursizeBluerCalculatorFactory;
		}

		/// <summary>
		/// The filter's coefficients for <paramref name="radius"/>: each output is <c>b</c> times its input plus
		/// <c>b1</c>, <c>b2</c> and <c>b3</c> times the three outputs before it (Young and van Vliet's recursive
		/// Gaussian). The GPU's recursive blur takes these so its sums match.
		/// </summary>
		public static (double B, double B1, double B2, double B3) Coefficients(double radius)
		{
			double s = (double)(radius * 0.5);
			double q = (double)((s < 2.5) ?
									3.97156 - 4.14554 * Math.Sqrt(1 - 0.26891 * s) :
									0.98711 * s - 0.96330);

			double q2 = (double)(q * q);
			double q3 = (double)(q2 * q);

			double b0 = (double)(1.0 / (1.578250 +
											2.444130 * q +
											1.428100 * q2 +
											0.422205 * q3));

			double b1 = (double)(2.44413 * q +
									  2.85619 * q2 +
									  1.26661 * q3);

			double b2 = (double)(-1.42810 * q2 +
									 -1.26661 * q3);

			double b3 = (double)(0.422205 * q3);

			double b = (double)(1 - (b1 + b2 + b3) * b0);

			return (b, b1 * b0, b2 * b0, b3 * b0);
		}

		public void blur_x(IImageByte img, double radius)
		{
			if (radius < 0.62) return;
			if (img.Width < 3) return;

			(double b, double b1, double b2, double b3) = Coefficients(radius);

			int w = img.Width;
			int h = img.Height;
			int wm = (int)w - 1;
			int x, y;

			int StartCreatingAt = (int)m_sum1.Count;
			for (int i = StartCreatingAt; i < w; i++)
			{
				m_sum1.Add(null);
				m_sum2.Add(null);
			}
			m_buf.Allocate(w);

			List<RecursizeBlurCalculator> Sum1Array = m_sum1;
			List<RecursizeBlurCalculator> Sum2Array = m_sum2;
			Color[] BufferArray = m_buf.Array;

			for (int i = StartCreatingAt; i < w; i++)
			{
				Sum1Array[i] = m_RecursizeBlurCalculatorFactory.CreateNew();
				Sum2Array[i] = m_RecursizeBlurCalculatorFactory.CreateNew();
			}

			for (y = 0; y < h; y++)
			{
				// The calculators write only the channels they blur (to_pix), so the rest keep the pixel's own.
				for (x = 0; x < w; ++x)
				{
					BufferArray[x] = img.GetPixel(x, y);
				}

				RecursizeBlurCalculator c = m_RecursizeBlurCalculatorFactory;
				c.from_pix(BufferArray[0]);
				Sum1Array[0].calc(b, b1, b2, b3, c, c, c, c);
				c.from_pix(BufferArray[1]);
				Sum1Array[1].calc(b, b1, b2, b3, c, Sum1Array[0], Sum1Array[0], Sum1Array[0]);
				c.from_pix(BufferArray[2]);
				Sum1Array[2].calc(b, b1, b2, b3, c, Sum1Array[1], Sum1Array[0], Sum1Array[0]);

				for (x = 3; x < w; ++x)
				{
					c.from_pix(BufferArray[x]);
					Sum1Array[x].calc(b, b1, b2, b3, c, Sum1Array[x - 1], Sum1Array[x - 2], Sum1Array[x - 3]);
				}

				Sum2Array[wm].calc(b, b1, b2, b3, Sum1Array[wm], Sum1Array[wm], Sum1Array[wm], Sum1Array[wm]);
				Sum2Array[wm - 1].calc(b, b1, b2, b3, Sum1Array[wm - 1], Sum2Array[wm], Sum2Array[wm], Sum2Array[wm]);
				Sum2Array[wm - 2].calc(b, b1, b2, b3, Sum1Array[wm - 2], Sum2Array[wm - 1], Sum2Array[wm], Sum2Array[wm]);
				Sum2Array[wm].to_pix(ref BufferArray[wm]);
				Sum2Array[wm - 1].to_pix(ref BufferArray[wm - 1]);
				Sum2Array[wm - 2].to_pix(ref BufferArray[wm - 2]);

				for (x = wm - 3; x >= 0; --x)
				{
					Sum2Array[x].calc(b, b1, b2, b3, Sum1Array[x], Sum2Array[x + 1], Sum2Array[x + 2], Sum2Array[x + 3]);
					Sum2Array[x].to_pix(ref BufferArray[x]);
				}

				img.copy_color_hspan(0, y, w, BufferArray, 0);
			}
		}

		public void blur_y(IImageByte img, double radius)
		{
			FormatTransposer img2 = new FormatTransposer(img);
			blur_x(img2, radius);
		}

		public void blur(IImageByte img, double radius)
		{
			blur_x(img, radius);
			blur_y(img, radius);
		}
	};

	//=================================================recursive_blur_calc_rgb
	public sealed class recursive_blur_calc_rgb : RecursizeBlurCalculator
	{
		public override RecursizeBlurCalculator CreateNew()
		{
			return new recursive_blur_calc_rgb();
		}

		public override void from_pix(Color c)
		{
			r = c.red;
			g = c.green;
			b = c.blue;
		}

		public override void calc(double b1, double b2, double b3, double b4,
			RecursizeBlurCalculator c1, RecursizeBlurCalculator c2, RecursizeBlurCalculator c3, RecursizeBlurCalculator c4)
		{
			r = b1 * c1.r + b2 * c2.r + b3 * c3.r + b4 * c4.r;
			g = b1 * c1.g + b2 * c2.g + b3 * c3.g + b4 * c4.g;
			b = b1 * c1.b + b2 * c2.b + b3 * c3.b + b4 * c4.b;
		}

		public override void to_pix(ref Color c)
		{
			c.red = ToByte(r);
			c.green = ToByte(g);
			c.blue = ToByte(b);
		}
	};

	//=================================================recursive_blur_calc_rgba
	public sealed class recursive_blur_calc_rgba : RecursizeBlurCalculator
	{
		public override RecursizeBlurCalculator CreateNew()
		{
			return new recursive_blur_calc_rgba();
		}

		public override void from_pix(Color c)
		{
			r = c.red;
			g = c.green;
			b = c.blue;
			a = c.alpha;
		}

		public override void calc(double b1, double b2, double b3, double b4,
			RecursizeBlurCalculator c1, RecursizeBlurCalculator c2, RecursizeBlurCalculator c3, RecursizeBlurCalculator c4)
		{
			r = b1 * c1.r + b2 * c2.r + b3 * c3.r + b4 * c4.r;
			g = b1 * c1.g + b2 * c2.g + b3 * c3.g + b4 * c4.g;
			b = b1 * c1.b + b2 * c2.b + b3 * c3.b + b4 * c4.b;
			a = b1 * c1.a + b2 * c2.a + b3 * c3.a + b4 * c4.a;
		}

		public override void to_pix(ref Color c)
		{
			c.red = ToByte(r);
			c.green = ToByte(g);
			c.blue = ToByte(b);
			c.alpha = ToByte(a);
		}
	};

	//================================================recursive_blur_calc_gray
	public sealed class recursive_blur_calc_gray : RecursizeBlurCalculator
	{
		public override RecursizeBlurCalculator CreateNew()
		{
			return new recursive_blur_calc_gray();
		}

		public override void from_pix(Color c)
		{
			r = c.red;
		}

		public override void calc(double b1, double b2, double b3, double b4,
			RecursizeBlurCalculator c1, RecursizeBlurCalculator c2, RecursizeBlurCalculator c3, RecursizeBlurCalculator c4)
		{
			r = b1 * c1.r + b2 * c2.r + b3 * c3.r + b4 * c4.r;
		}

		public override void to_pix(ref Color c)
		{
			// A grey value in every colour channel, so a grey blender's luminance copy reads it back unchanged.
			c.red = c.green = c.blue = ToByte(r);
		}
	};
}