// <auto-generated>
// Hack to disable analyzers and their warnings - too many issues to address
// </auto-generated>
using MatterHackers.VectorMath;

//----------------------------------------------------------------------------
// Anti-Grain Geometry - Version 2.4
// Copyright (C) 2002-2005 Maxim Shemanarev (http://www.antigrain.com)
//
// C# port by: Lars Brubaker
//                  larsbrubaker@gmail.com
// Copyright (C) 2007
//
// Permission to copy, use, modify, sell and distribute this software
// is granted provided this copyright notice appears in all copies.
// This software is provided "as is" without express or implied
// warranty, and with no claim as to its suitability for any purpose.
//
//----------------------------------------------------------------------------
// Contact: mcseem@antigrain.com
//          mcseemagg@yahoo.com
//          http://www.antigrain.com
//----------------------------------------------------------------------------
//
// Class gsv_text
//
//----------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MatterHackers.Agg.VertexSource
{
	[Obsolete("All of these should use the new font stuff.  You probably want a StringPrinter or a TextWidget in this spot.")]
	public sealed class gsv_text : IVertexSource
	{
		private enum status
		{
			initial,
			next_char,
			start_glyph,
			glyph
		};

		private double m_StartX;
		private double m_StartY;
		private double m_CurrentX;
		private double m_CurrentY;
		private double m_WidthRatioOfHeight;
		private double m_FontSize;
		private double m_SpaceBetweenCharacters;
		private double m_SpaceBetweenLines;
		private string m_Text;
		private int m_CurrentCharacterIndex;
		private byte[] m_font;
		private status m_status;
		private int m_StartOfIndicesIndex;
		private int m_StartOfGlyphsIndex;
		private int m_BeginGlyphIndex;
		private int m_EndGlyphIndex;
		private double m_WidthScaleRatio;
		private double m_HeightScaleRatio;
		private bool m_Flip;

		public double FontSize
		{
			get
			{
				return m_FontSize;
			}
			set
			{
				m_FontSize = value;
				double base_height = translateIndex(4);
				m_HeightScaleRatio = m_FontSize / base_height;
				m_WidthScaleRatio = m_HeightScaleRatio * m_WidthRatioOfHeight;
			}
		}

		public double AscenderHeight
		{
			get
			{
				return m_FontSize * .15;
			}
		}

		public double DescenderHeight
		{
			get
			{
				return m_FontSize * .2;
			}
		}

		public gsv_text()
		{
			m_font = CGSVDefaultFont.gsv_default_font;
			m_CurrentX = 0.0;
			m_CurrentY = 0.0;
			m_StartX = 0.0;
			m_StartY = 0.0;
			m_WidthRatioOfHeight = 1;
			FontSize = 0.0;
			m_SpaceBetweenCharacters = 0.0;
			m_status = status.initial;

			m_SpaceBetweenLines = 0.0;

			// C++ starts with an empty string, so a gsv_text that was never given text draws nothing.
			m_Text = string.Empty;
		}

        /*
		public void font(void* font)
		{
			m_font = font;
			if(m_font == 0) m_font = &m_loaded_font[0];
		}
		 */

        public ulong GetLongHashCode(ulong hash = 14695981039346656037)
        {
            foreach (var vertex in this.Vertices())
            {
                hash = vertex.GetLongHashCode(hash);
            }

            return hash;
        }

        public void load_font(string file)
		{
			throw new System.NotImplementedException();
			/*
			m_loaded_font.resize(0);
			FILE* fd = fopen(file, "rb");
			if(fd)
			{
				int len;

				fseek(fd, 0l, SEEK_END);
				len = ftell(fd);
				fseek(fd, 0l, SEEK_SET);
				if(len > 0)
				{
					m_loaded_font.resize(len);
					fread(&m_loaded_font[0], 1, len, fd);
					m_font = &m_loaded_font[0];
				}
				fclose(fd);
			}
			 */
		}

		// This will set the desired height.  NOTE: The font may not render at the size that you say.
		// It depends on the way the font was originally created.  A 24 Point font may not actually be 24 points high
		public void SetFontSize(double fontSize)
		{
			SetFontSizeAndWidthRatio(fontSize, 1.0);
		}

		public void SetFontSizeAndWidthRatio(double fontSize, double widthRatioOfHeight)
		{
			if (fontSize == 0 || widthRatioOfHeight == 0)
			{
				throw new System.Exception("You can't have a font with 0 width or height.  Nothing will render.");
			}

			m_WidthRatioOfHeight = widthRatioOfHeight;
			FontSize = fontSize;

			m_SpaceBetweenLines = FontSize * 1.5;
		}

		/// <summary>
		/// C++ gsv_text::size: glyph height and width in output units, each scaled from the font's base
		/// height separately (a width of 0 means the height scale). Unlike <see cref="SetFontSizeAndWidthRatio"/>
		/// this divides the width by the base height directly, so the scale factors are C++'s bit for bit.
		/// </summary>
		public void size(double height, double width)
		{
			m_FontSize = height;
			double base_height = translateIndex(4);
			m_HeightScaleRatio = height / base_height;
			m_WidthScaleRatio = (width == 0.0) ? m_HeightScaleRatio : width / base_height;
		}

		public void SetSpaceBetweenCharacters(double spaceBetweenCharacters)
		{
			m_SpaceBetweenCharacters = spaceBetweenCharacters;
		}

		public void line_space(double spaceBetweenLines)
		{
			m_SpaceBetweenLines = spaceBetweenLines;
		}

		/// <summary>
		/// C++ gsv_text::flip: glyphs drawn with y down (each glyph's y steps negated, and a new line moving
		/// down the y axis) for a y-down surface. Off by default.
		/// </summary>
		public void flip(bool flip)
		{
			m_Flip = flip;
		}

		public void start_point(double x, double y)
		{
			m_CurrentX = m_StartX = x;
			m_CurrentY = m_StartY = y;
		}

		public string Text
		{
			get
			{
				return m_Text;
			}
			set
			{
				m_Text = value;
			}
		}

		/// <summary>C++ gsv_text::text; null is the empty string, as in C++.</summary>
		public void text(string text)
		{
			m_Text = text ?? string.Empty;
		}

		private ushort translateIndex(int indicesIndex)
		{
			ushort v;
			v = m_font[indicesIndex + 0];
			v |= (ushort)(m_font[indicesIndex + 1] << 8);
			return v;
		}

		/// <summary>The text's outline from the start point: a rewind, then every vertex up to the stop.</summary>
		public IEnumerable<VertexData> Vertices()
		{
			Rewind(0);
			while (true)
			{
				FlagsAndCommand command = Vertex(out double x, out double y);
				yield return new VertexData(command, x, y);
				if (command == FlagsAndCommand.Stop)
				{
					yield break;
				}
			}
		}

		public void Rewind(int nothing)
		{
			m_status = status.initial;

			// C++ gsv_text::rewind leaves the pen where the last pass ended, so a second pass (the GPU reads a
			// stroke's source more than once) drew the text shifted by its own width. Every pass starts over.
			m_CurrentX = m_StartX;
			m_CurrentY = m_StartY;
			if (m_font == null) return;

			m_StartOfIndicesIndex = translateIndex(0);

			m_StartOfGlyphsIndex = m_StartOfIndicesIndex + 257 * 2; // one for x one for y
			m_CurrentCharacterIndex = 0;
		}

		private void GetSize(char characterToMeasure, out double width, out double height)
		{
			width = 0;
			height = 0;
			if (m_font == null)
			{
				return;
			}

			int maskedChracter = (int)(characterToMeasure & 0xFF);
			if (maskedChracter == '\r' || maskedChracter == '\n')
			{
				height -= (FontSize + m_SpaceBetweenLines);
				return;
			}

			int maskedChracterGlyphIndex = maskedChracter * 2; // we have an x and y in the array so it's * 2.
			int BeginGlyphIndex = m_StartOfGlyphsIndex + translateIndex(m_StartOfIndicesIndex + maskedChracterGlyphIndex);
			int EndGlyphIndex = m_StartOfGlyphsIndex + translateIndex(m_StartOfIndicesIndex + maskedChracterGlyphIndex + 2);

			do
			{
				if (BeginGlyphIndex >= EndGlyphIndex)
				{
					return; // the character has no glyph
				}

				unchecked
				{
					int DeltaX = (sbyte)m_font[BeginGlyphIndex++];
					sbyte yc = (sbyte)m_font[BeginGlyphIndex++];

					yc <<= 1;
					yc >>= 1;
					int DeltaY = (int)(yc);
					width += (double)(DeltaX) * m_WidthScaleRatio;
					height += (double)(DeltaY) * m_HeightScaleRatio;
				}
			} while (true);
		}

		public int GetCharacterIndexToStartBefore(Vector2 position)
		{
			int clostestIndex = -1;
			double clostestDist = double.MaxValue;
			Vector2 offset;
			offset.X = 0;
			offset.Y = 0;
			int characterToMeasureStartIndexInclusive = 0;
			int characterToMeasureEndIndexInclusive = m_Text.Length - 1;
			if (m_Text.Length > 0)
			{
				characterToMeasureStartIndexInclusive = Math.Max(0, Math.Min(characterToMeasureStartIndexInclusive, m_Text.Length - 1));
				characterToMeasureEndIndexInclusive = Math.Max(0, Math.Min(characterToMeasureEndIndexInclusive, m_Text.Length - 1));
				for (int i = characterToMeasureStartIndexInclusive; i <= characterToMeasureEndIndexInclusive; i++)
				{
					Vector2 delta = offset - position;
					double distToChar = delta.Length;
					if (distToChar < clostestDist)
					{
						clostestDist = distToChar;
						clostestIndex = i;
					}

					char singleChar = m_Text[i];
					if (singleChar == '\r' || singleChar == '\n')
					{
						offset.X = 0;
						offset.Y -= FontSize + m_SpaceBetweenLines;
					}
					else
					{
						double sigleWidth;
						double sigleHeight;
						GetSize(singleChar, out sigleWidth, out sigleHeight);
						offset.X += sigleWidth + m_SpaceBetweenCharacters;
						offset.Y += sigleHeight;
					}
				}

				Vector2 lastDelta = offset - position;
				double lastDistToChar = lastDelta.Length;
				if (lastDistToChar < clostestDist)
				{
					clostestDist = lastDistToChar;
					// we need to start after the lats character, or before the character after the last.
					clostestIndex = characterToMeasureEndIndexInclusive + 1;
				}
			}

			return clostestIndex;
		}

		public void GetSize(out Vector2 pixelSize)
		{
			GetSize(0, m_Text.Length - 1, out pixelSize);
		}

		public void GetSize(int characterToMeasureStartIndexInclusive, int characterToMeasureEndIndexInclusive, out Vector2 pixelSize)
		{
			double currentX = 0;
			pixelSize.X = 0;
			pixelSize.Y = 0;
			if (m_Text.Length > 0)
			{
				characterToMeasureStartIndexInclusive = Math.Max(0, Math.Min(characterToMeasureStartIndexInclusive, m_Text.Length - 1));
				characterToMeasureEndIndexInclusive = Math.Max(0, Math.Min(characterToMeasureEndIndexInclusive, m_Text.Length - 1));
				for (int i = characterToMeasureStartIndexInclusive; i <= characterToMeasureEndIndexInclusive; i++)
				{
					char singleChar = m_Text[i];
					if (singleChar == '\r' || singleChar == '\n')
					{
						currentX = 0;
						pixelSize.Y -= FontSize + m_SpaceBetweenLines;
					}
					else
					{
						double sigleWidth;
						double sigleHeight;
						GetSize(singleChar, out sigleWidth, out sigleHeight);
						currentX += sigleWidth + m_SpaceBetweenCharacters;
						pixelSize.X = Math.Max(currentX, pixelSize.X);
						pixelSize.Y += sigleHeight;
					}
				}
			}
		}

		public FlagsAndCommand Vertex(out double x, out double y)
		{
			x = 0;
			y = 0;
			bool quit = false;

			while (!quit)
			{
				switch (m_status)
				{
					case status.initial:
						if (m_font == null)
						{
							quit = true;
							break;
						}
						m_status = status.next_char;
						goto case status.next_char;

					case status.next_char:
						if (m_CurrentCharacterIndex == m_Text.Length)
						{
							quit = true;
							break;
						}
						int maskedChracter = (int)((m_Text[m_CurrentCharacterIndex++]) & 0xFF);
						if (maskedChracter == '\r' || maskedChracter == '\n')
						{
							m_CurrentX = m_StartX;
							m_CurrentY -= m_Flip ? -FontSize - m_SpaceBetweenLines : FontSize + m_SpaceBetweenLines;
							break;
						}
						int maskedChracterGlyphIndex = maskedChracter * 2; // we have an x and y in the array so it's * 2.
						m_BeginGlyphIndex = m_StartOfGlyphsIndex + translateIndex(m_StartOfIndicesIndex + maskedChracterGlyphIndex);
						m_EndGlyphIndex = m_StartOfGlyphsIndex + translateIndex(m_StartOfIndicesIndex + maskedChracterGlyphIndex + 2);
						m_status = status.start_glyph;
						goto case status.start_glyph;

					case status.start_glyph:
						x = m_CurrentX;
						y = m_CurrentY;
						m_status = status.glyph;
						return FlagsAndCommand.MoveTo;

					case status.glyph:
						if (m_BeginGlyphIndex >= m_EndGlyphIndex)
						{
							m_status = status.next_char;
							m_CurrentX += m_SpaceBetweenCharacters;
							break;
						}

						sbyte IsAMoveTo_Flag;
						unchecked
						{
							int DeltaX = (sbyte)m_font[m_BeginGlyphIndex++];
							sbyte yc = (sbyte)m_font[m_BeginGlyphIndex++];

							IsAMoveTo_Flag = (sbyte)(yc & 0x80);
							yc <<= 1;
							yc >>= 1;
							int DeltaY = (int)(yc);
							m_CurrentX += (double)(DeltaX) * m_WidthScaleRatio;
							m_CurrentY += (double)(DeltaY) * (m_Flip ? -m_HeightScaleRatio : m_HeightScaleRatio);
						}
						x = m_CurrentX;
						y = m_CurrentY;
						if (IsAMoveTo_Flag != 0)
						{
							return FlagsAndCommand.MoveTo;
						}

						return FlagsAndCommand.LineTo;

					default:
						throw new System.Exception("Unknown Status");
				}
			}

			return FlagsAndCommand.Stop;
		}
	};
}
