/*
Copyright (c) 2026, Lars Brubaker
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the FreeBSD Project.
*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MatterHackers.Agg;
using MatterHackers.Agg.Image;
using MatterHackers.Agg.LcdCoverage;
using MatterHackers.Agg.Transform;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace Agg.Tests.Agg
{
	/// <summary>
	/// Byte-exactness fixture: rebuilds a fixed set of vector paths through the C# LCD pipeline and
	/// asserts the result is <b>byte for byte</b> what the agg-gui Rust reference produced for the same
	/// inputs. This is the test that makes "the port produces the exact same solution" a checked claim
	/// rather than an intention.
	/// </summary>
	/// <remarks>
	/// The fixture blobs and their manifest live in <c>TestData\LcdFixture</c> and are generated by
	/// <c>agg-gui\examples\lcd_reference_fixture.rs</c> in the reference checkout:
	/// <code>cargo run -p agg-gui --example lcd_reference_fixture -- &lt;out_dir&gt;</code>
	/// That harness drives the reference's real production code (<c>LcdMaskBuilder</c>,
	/// <c>composite_lcd_mask</c>) - nothing about the algorithm is restated on either side.
	/// <para>
	/// Geometry, transforms and clip rects come out of the manifest as raw IEEE-754 bit patterns rather
	/// than being re-typed here as literals, so the two sides cannot drift apart in the inputs. Only the
	/// case <i>names</i> are duplicated, once each, in <see cref="AllCaseNames"/> and
	/// <see cref="CompositeCaseNames"/>; every test feeds off those through
	/// <see cref="MethodDataSourceAttribute"/>, and the two guards below fail if either list stops
	/// matching the manifest.
	/// </para>
	/// <para>
	/// <b>Stage attribution.</b> Each case is checked at three points, which is what makes a failure
	/// diagnosable: <see cref="GrayCollapseMatchesRustReference"/> is a pure function of the
	/// 3x-supersampled gray raster buffer, so if it passes while
	/// <see cref="LcdMaskMatchesRustReference"/> fails the divergence is in <see cref="LcdFilter"/>; if
	/// the gray check itself fails the divergence is in the raster stage (the historical suspect there is
	/// gray blender rounding - see <see cref="BlenderGrayExact"/>). The composite check runs both from
	/// the locally rebuilt mask and from the reference's own mask bytes, which separates a stage-3
	/// arithmetic difference from an inherited stage-1/2 one.
	/// </para>
	/// </remarks>
	public class LcdRustFixtureTests
	{
		/// <summary>
		/// Every case in the manifest, and the <b>only</b> place the case names are written down on this
		/// side: all three per-case tests take their arguments from here, so a name cannot be exercised by
		/// one stage and skipped by another. <see cref="FixtureCoversEveryCaseInTheManifest"/> keeps the
		/// list honest against the manifest itself.
		/// </summary>
		public static IEnumerable<string> AllCaseNames()
		{
			yield return "rect_frac_identity";
			yield return "rect_frac_translate";
			yield return "rect_rot30";
			yield return "rect_scale375";
			yield return "sliver_triangle";
			yield return "sliver_triangle_rot30";
			yield return "shallow_wedge";
			yield return "two_overlap_nonzero";
			yield return "star_nonzero";
			yield return "star_evenodd";
			yield return "clip_frac";
			yield return "circle_cubic";
			yield return "circle_cubic_rot30_scale";
		}

		/// <summary>
		/// The subset of cases that also pin stage 3. Not every case needs one - the composite is a
		/// per-pixel blend, so two destinations (opaque-over-light and translucent-over-split) cover it -
		/// but <see cref="CompositeTestsCoverEveryCompositeInTheManifest"/> requires this to be exactly the
		/// set the manifest carries a composite section for.
		/// </summary>
		public static IEnumerable<string> CompositeCaseNames()
		{
			yield return "rect_frac_identity";
			yield return "star_nonzero";
		}

		/// <summary>
		/// The subset of cases that also pin the two-plane <see cref="LcdBuffer"/> stage, kept honest by
		/// <see cref="BufferTestsCoverEveryBufferInTheManifest"/>. One case is enough: the planes are a
		/// per-pixel function of the mask (pinned per case above) and the composite, so a second would add
		/// geometry rather than arithmetic.
		/// </summary>
		public static IEnumerable<string> BufferCaseNames()
		{
			yield return "star_nonzero";
		}

		/// <summary>
		/// The LCD mask - stage 1 (3x gray raster) plus stage 2 (integer 5-tap filter) - against the
		/// reference's <c>.lcd</c> dump.
		/// </summary>
		[Test]
		[MethodDataSource(nameof(AllCaseNames))]
		public async Task LcdMaskMatchesRustReference(string caseName)
		{
			LcdFixtureCase fixtureCase = LcdFixtureManifest.Load().Case(caseName);
			LcdMask mask = fixtureCase.BuildMask(gray: false);

			await AssertBytesEqual(
				fixtureCase.ReadLcdBlob(),
				mask.Data,
				caseName,
				"LCD mask",
				fixtureCase.MaskWidth,
				bytesPerPixel: 3,
				channelNames: "RGB");
		}

		/// <summary>
		/// The gray-collapse mask against the reference's <c>.gray</c> dump. Same raster, different
		/// finalize - so this isolates the raster stage from the 5-tap filter (see the class remarks).
		/// </summary>
		[Test]
		[MethodDataSource(nameof(AllCaseNames))]
		public async Task GrayCollapseMatchesRustReference(string caseName)
		{
			LcdFixtureCase fixtureCase = LcdFixtureManifest.Load().Case(caseName);
			LcdMask mask = fixtureCase.BuildMask(gray: true);

			await AssertBytesEqual(
				fixtureCase.ReadGrayBlob(),
				mask.Data,
				caseName,
				"gray-collapse mask",
				fixtureCase.MaskWidth,
				bytesPerPixel: 3,
				channelNames: "RGB");
		}

		/// <summary>
		/// Stage 3 against the reference's <c>.dst</c> dump: the mask composited over a known destination
		/// in a known source color at a known integer origin. Asserted twice - once end to end from the
		/// locally rebuilt mask, once from the reference's own mask bytes, so a composite-arithmetic
		/// difference is distinguishable from an inherited raster/filter one.
		/// </summary>
		[Test]
		[MethodDataSource(nameof(CompositeCaseNames))]
		public async Task CompositeMatchesRustReference(string caseName)
		{
			LcdFixtureCase fixtureCase = LcdFixtureManifest.Load().Case(caseName);
			LcdFixtureComposite composite = fixtureCase.Composite;
			await Assert.That(composite).IsNotNull();

			byte[] expected = fixtureCase.ReadCompositeBlob();

			byte[] fromReferenceMask = composite.Run(new LcdMask(
				fixtureCase.ReadLcdBlob(), fixtureCase.MaskWidth, fixtureCase.MaskHeight));
			await AssertBytesEqual(
				expected,
				fromReferenceMask,
				caseName,
				"composite of the reference mask",
				composite.Width,
				bytesPerPixel: 4,
				channelNames: "RGBA");

			byte[] endToEnd = composite.Run(fixtureCase.BuildMask(gray: false));
			await AssertBytesEqual(
				expected,
				endToEnd,
				caseName,
				"composite of the locally rebuilt mask",
				composite.Width,
				bytesPerPixel: 4,
				channelNames: "RGBA");
		}

		/// <summary>
		/// The two-plane buffer stage against the reference's <c>.bufcolor</c> / <c>.bufalpha</c> dumps: the
		/// same paths painted through <see cref="LcdBuffer.FillPath"/> over the same cleared background, in
		/// the same fill color. Both planes are compared, because they carry different information - the
		/// color plane could match while the per-channel alpha (the reason the buffer exists) was wrong.
		/// <para>
		/// This is also the only fixture stage that reaches <see cref="BoundedMaskBuilder"/>'s own sizing and
		/// integer origin, since the mask stages are handed their size by the manifest. A displaced origin
		/// moves every painted byte and shows up here immediately.
		/// </para>
		/// </summary>
		[Test]
		[MethodDataSource(nameof(BufferCaseNames))]
		public async Task LcdBufferFillPathMatchesRustReference(string caseName)
		{
			LcdFixtureCase fixtureCase = LcdFixtureManifest.Load().Case(caseName);
			await Assert.That(fixtureCase.Buffer).IsNotNull();

			LcdBuffer buffer = fixtureCase.BuildBuffer();

			await AssertBytesEqual(
				fixtureCase.ReadBufferColorBlob(),
				buffer.ColorPlane,
				caseName,
				"LcdBuffer color plane",
				fixtureCase.Buffer.Width,
				bytesPerPixel: 3,
				channelNames: "RGB");
			await AssertBytesEqual(
				fixtureCase.ReadBufferAlphaBlob(),
				buffer.AlphaPlane,
				caseName,
				"LcdBuffer alpha plane",
				fixtureCase.Buffer.Width,
				bytesPerPixel: 3,
				channelNames: "RGB");
		}

		/// <summary>
		/// Same guard as <see cref="CompositeTestsCoverEveryCompositeInTheManifest"/>, for the buffer stage:
		/// a <c>.bufcolor</c> / <c>.bufalpha</c> pair generated on the reference side but not named here
		/// would be checked in and never compared against anything.
		/// </summary>
		[Test]
		public async Task BufferTestsCoverEveryBufferInTheManifest()
		{
			LcdFixtureManifest manifest = LcdFixtureManifest.Load();

			await Assert.That(Sorted(manifest.BufferCaseNames)).IsEquivalentTo(Sorted(BufferCaseNames()));
		}

		/// <summary>
		/// A regenerated fixture that adds cases would otherwise sit unexercised, and one that renames or
		/// drops a case would silently reduce coverage. Also pins the filter parameters the reference used:
		/// the byte-exact integer path is only taken at primary weight 1/3 and gamma 1, so if the fixture
		/// were ever regenerated with other values the rebuild here would have to pass them through.
		/// </summary>
		[Test]
		public async Task FixtureCoversEveryCaseInTheManifest()
		{
			LcdFixtureManifest manifest = LcdFixtureManifest.Load();

			await Assert.That(Sorted(manifest.CaseNames)).IsEquivalentTo(Sorted(AllCaseNames()));
			await Assert.That(manifest.PrimaryWeight).IsEqualTo(LcdFilter.DefaultPrimaryWeight);
			await Assert.That(manifest.Gamma).IsEqualTo(LcdFilter.DefaultGamma);
		}

		/// <summary>
		/// The composite is the one stage whose coverage is a deliberate subset, which makes it the one
		/// place a regenerated fixture can quietly lose coverage: adding a composite section on the
		/// reference side without adding the name to <see cref="CompositeCaseNames"/> would check in a
		/// <c>.dst</c> blob that nothing ever compares against. Requiring set equality (not containment)
		/// also catches the reverse, a name here whose case no longer has a composite.
		/// </summary>
		[Test]
		public async Task CompositeTestsCoverEveryCompositeInTheManifest()
		{
			LcdFixtureManifest manifest = LcdFixtureManifest.Load();

			await Assert.That(Sorted(manifest.CompositeCaseNames)).IsEquivalentTo(Sorted(CompositeCaseNames()));
		}

		private static string[] Sorted(IEnumerable<string> names)
		{
			return names.OrderBy(n => n, StringComparer.Ordinal).ToArray();
		}

		/// <summary>
		/// Compares two blobs and, on a mismatch, reports the case, the stage, the first differing byte
		/// offset with its expected and actual values, the (x, y, channel) that offset addresses, how many
		/// bytes differ in total and the largest difference - enough to tell "one channel is off by one at
		/// an edge" from "the whole raster moved".
		/// </summary>
		private static async Task AssertBytesEqual(
			byte[] expected,
			byte[] actual,
			string caseName,
			string stage,
			int width,
			int bytesPerPixel,
			string channelNames)
		{
			string message = Describe(expected, actual, caseName, stage, width, bytesPerPixel, channelNames);
			await Assert.That(message).IsNull().Because(message ?? string.Empty);
		}

		/// <summary>Null when the blobs are byte-identical, otherwise the failure report.</summary>
		private static string Describe(
			byte[] expected,
			byte[] actual,
			string caseName,
			string stage,
			int width,
			int bytesPerPixel,
			string channelNames)
		{
			if (expected.Length != actual.Length)
			{
				return $"{caseName} / {stage}: length {actual.Length}, reference length {expected.Length}.";
			}

			int first = -1;
			int differing = 0;
			int maxDelta = 0;
			for (int i = 0; i < expected.Length; i++)
			{
				if (expected[i] != actual[i])
				{
					if (first < 0)
					{
						first = i;
					}

					differing++;
					maxDelta = Math.Max(maxDelta, Math.Abs(expected[i] - actual[i]));
				}
			}

			if (first < 0)
			{
				return null;
			}

			int pixel = first / bytesPerPixel;
			int x = pixel % width;
			int y = pixel / width;
			char channel = channelNames[first % bytesPerPixel];
			return $"{caseName} / {stage}: first difference at byte {first} "
				+ $"(x {x}, y {y}, channel {channel}) - reference {expected[first]}, port {actual[first]}. "
				+ $"{differing} of {expected.Length} bytes differ, largest difference {maxDelta}. "
				+ "Y is measured from the bottom row.";
		}
	}
}
