{{{
    globalThis.__HAVE_EMDAWNWEBGPU_SIG_INFO = true;
    null;
}}}const webgpuSigs = {
    // emscripten_webgpu_*
    emscripten_webgpu_get_device__sig: 'p',
    emscripten_webgpu_release_js_handle__sig: 'vi',
    emscripten_webgpu_export_adapter__sig: 'ip',
    emscripten_webgpu_import_adapter__sig: 'pi',
    emscripten_webgpu_export_bind_group__sig: 'ip',
    emscripten_webgpu_import_bind_group__sig: 'pi',
    emscripten_webgpu_export_bind_group_layout__sig: 'ip',
    emscripten_webgpu_import_bind_group_layout__sig: 'pi',
    emscripten_webgpu_export_buffer__sig: 'ip',
    emscripten_webgpu_import_buffer__sig: 'pi',
    emscripten_webgpu_export_command_buffer__sig: 'ip',
    emscripten_webgpu_import_command_buffer__sig: 'pi',
    emscripten_webgpu_export_command_encoder__sig: 'ip',
    emscripten_webgpu_import_command_encoder__sig: 'pi',
    emscripten_webgpu_export_compute_pipeline__sig: 'ip',
    emscripten_webgpu_import_compute_pipeline__sig: 'pi',
    emscripten_webgpu_export_device__sig: 'ip',
    emscripten_webgpu_import_device__sig: 'pi',
    emscripten_webgpu_export_external_texture__sig: 'ip',
    emscripten_webgpu_import_external_texture__sig: 'pi',
    emscripten_webgpu_export_instance__sig: 'ip',
    emscripten_webgpu_import_instance__sig: 'pi',
    emscripten_webgpu_export_pipeline_layout__sig: 'ip',
    emscripten_webgpu_import_pipeline_layout__sig: 'pi',
    emscripten_webgpu_export_query_set__sig: 'ip',
    emscripten_webgpu_import_query_set__sig: 'pi',
    emscripten_webgpu_export_queue__sig: 'ip',
    emscripten_webgpu_import_queue__sig: 'pi',
    emscripten_webgpu_export_render_bundle__sig: 'ip',
    emscripten_webgpu_import_render_bundle__sig: 'pi',
    emscripten_webgpu_export_render_pipeline__sig: 'ip',
    emscripten_webgpu_import_render_pipeline__sig: 'pi',
    emscripten_webgpu_export_sampler__sig: 'ip',
    emscripten_webgpu_import_sampler__sig: 'pi',
    emscripten_webgpu_export_shader_module__sig: 'ip',
    emscripten_webgpu_import_shader_module__sig: 'pi',
    emscripten_webgpu_export_surface__sig: 'ip',
    emscripten_webgpu_import_surface__sig: 'pi',
    emscripten_webgpu_export_texture__sig: 'ip',
    emscripten_webgpu_import_texture__sig: 'pi',
    emscripten_webgpu_export_texture_view__sig: 'ip',
    emscripten_webgpu_import_texture_view__sig: 'pi',
    emscripten_webgpu_export_compute_pass_encoder__sig: 'ip',
    emscripten_webgpu_import_compute_pass_encoder__sig: 'pi',
    emscripten_webgpu_export_render_bundle_encoder__sig: 'ip',
    emscripten_webgpu_import_render_bundle_encoder__sig: 'pi',
    emscripten_webgpu_export_render_pass_encoder__sig: 'ip',
    emscripten_webgpu_import_render_pass_encoder__sig: 'pi',

    // wgpu*
    wgpuCreateInstance__sig: 'pp',
    wgpuGetInstanceFeatures__sig: 'vp',
    wgpuGetInstanceLimits__sig: 'ip',
    wgpuHasInstanceFeature__sig: 'ii',
    //wgpuGetProcAddress__sig: 'p(string view)',
    wgpuAdapterGetFeatures__sig: 'vpp',
    wgpuAdapterGetInfo__sig: 'ipp',
    wgpuAdapterGetLimits__sig: 'ipp',
    wgpuAdapterHasFeature__sig: 'ipi',
    //wgpuAdapterRequestDevice__sig: '(future)pp(request device callback info)',
    wgpuAdapterAddRef__sig: 'vp',
    wgpuAdapterRelease__sig: 'vp',
    //wgpuBindGroupSetLabel__sig: 'vp(string view)',
    wgpuBindGroupAddRef__sig: 'vp',
    wgpuBindGroupRelease__sig: 'vp',
    //wgpuBindGroupLayoutSetLabel__sig: 'vp(string view)',
    wgpuBindGroupLayoutAddRef__sig: 'vp',
    wgpuBindGroupLayoutRelease__sig: 'vp',
    wgpuBufferDestroy__sig: 'vp',
    wgpuBufferGetConstMappedRange__sig: 'pppp',
    wgpuBufferGetMappedRange__sig: 'pppp',
    wgpuBufferGetMapState__sig: 'ip',
    wgpuBufferGetSize__sig: 'jp',
    wgpuBufferGetUsage__sig: 'jp',
    //wgpuBufferMapAsync__sig: '(future)pjpp(buffer map callback info)',
    wgpuBufferReadMappedRange__sig: 'ipppp',
    //wgpuBufferSetLabel__sig: 'vp(string view)',
    wgpuBufferUnmap__sig: 'vp',
    wgpuBufferWriteMappedRange__sig: 'ipppp',
    wgpuBufferAddRef__sig: 'vp',
    wgpuBufferRelease__sig: 'vp',
    //wgpuCommandBufferSetLabel__sig: 'vp(string view)',
    wgpuCommandBufferAddRef__sig: 'vp',
    wgpuCommandBufferRelease__sig: 'vp',
    wgpuCommandEncoderBeginComputePass__sig: 'ppp',
    wgpuCommandEncoderBeginRenderPass__sig: 'ppp',
    wgpuCommandEncoderClearBuffer__sig: 'vppjj',
    wgpuCommandEncoderCopyBufferToBuffer__sig: 'vppjpjj',
    wgpuCommandEncoderCopyBufferToTexture__sig: 'vpppp',
    wgpuCommandEncoderCopyTextureToBuffer__sig: 'vpppp',
    wgpuCommandEncoderCopyTextureToTexture__sig: 'vpppp',
    wgpuCommandEncoderFinish__sig: 'ppp',
    //wgpuCommandEncoderInsertDebugMarker__sig: 'vp(string view)',
    wgpuCommandEncoderPopDebugGroup__sig: 'vp',
    //wgpuCommandEncoderPushDebugGroup__sig: 'vp(string view)',
    wgpuCommandEncoderResolveQuerySet__sig: 'vppiipj',
    //wgpuCommandEncoderSetLabel__sig: 'vp(string view)',
    wgpuCommandEncoderWriteTimestamp__sig: 'vppi',
    wgpuCommandEncoderAddRef__sig: 'vp',
    wgpuCommandEncoderRelease__sig: 'vp',
    wgpuComputePipelineGetBindGroupLayout__sig: 'ppi',
    //wgpuComputePipelineSetLabel__sig: 'vp(string view)',
    wgpuComputePipelineAddRef__sig: 'vp',
    wgpuComputePipelineRelease__sig: 'vp',
    wgpuDeviceCreateBindGroup__sig: 'ppp',
    wgpuDeviceCreateBindGroupLayout__sig: 'ppp',
    wgpuDeviceCreateBuffer__sig: 'ppp',
    wgpuDeviceCreateCommandEncoder__sig: 'ppp',
    wgpuDeviceCreateComputePipeline__sig: 'ppp',
    //wgpuDeviceCreateComputePipelineAsync__sig: '(future)pp(create compute pipeline async callback info)',
    wgpuDeviceCreatePipelineLayout__sig: 'ppp',
    wgpuDeviceCreateQuerySet__sig: 'ppp',
    wgpuDeviceCreateRenderBundleEncoder__sig: 'ppp',
    wgpuDeviceCreateRenderPipeline__sig: 'ppp',
    //wgpuDeviceCreateRenderPipelineAsync__sig: '(future)pp(create render pipeline async callback info)',
    wgpuDeviceCreateSampler__sig: 'ppp',
    wgpuDeviceCreateShaderModule__sig: 'ppp',
    wgpuDeviceCreateTexture__sig: 'ppp',
    wgpuDeviceDestroy__sig: 'vp',
    wgpuDeviceGetAdapterInfo__sig: 'ipp',
    wgpuDeviceGetFeatures__sig: 'vpp',
    wgpuDeviceGetLimits__sig: 'ipp',
    //wgpuDeviceGetLostFuture__sig: '(future)p',
    wgpuDeviceGetQueue__sig: 'pp',
    wgpuDeviceHasFeature__sig: 'ipi',
    //wgpuDevicePopErrorScope__sig: '(future)p(pop error scope callback info)',
    wgpuDevicePushErrorScope__sig: 'vpi',
    //wgpuDeviceSetLabel__sig: 'vp(string view)',
    wgpuDeviceAddRef__sig: 'vp',
    wgpuDeviceRelease__sig: 'vp',
    //wgpuExternalTextureSetLabel__sig: 'vp(string view)',
    wgpuExternalTextureAddRef__sig: 'vp',
    wgpuExternalTextureRelease__sig: 'vp',
    wgpuInstanceCreateSurface__sig: 'ppp',
    wgpuInstanceGetWGSLLanguageFeatures__sig: 'vpp',
    wgpuInstanceHasWGSLLanguageFeature__sig: 'ipi',
    wgpuInstanceProcessEvents__sig: 'vp',
    //wgpuInstanceRequestAdapter__sig: '(future)pp(request adapter callback info)',
    wgpuInstanceWaitAny__sig: 'ipppj',
    wgpuInstanceAddRef__sig: 'vp',
    wgpuInstanceRelease__sig: 'vp',
    //wgpuPipelineLayoutSetLabel__sig: 'vp(string view)',
    wgpuPipelineLayoutAddRef__sig: 'vp',
    wgpuPipelineLayoutRelease__sig: 'vp',
    wgpuQuerySetDestroy__sig: 'vp',
    wgpuQuerySetGetCount__sig: 'ip',
    wgpuQuerySetGetType__sig: 'ip',
    //wgpuQuerySetSetLabel__sig: 'vp(string view)',
    wgpuQuerySetAddRef__sig: 'vp',
    wgpuQuerySetRelease__sig: 'vp',
    //wgpuQueueOnSubmittedWorkDone__sig: '(future)p(queue work done callback info)',
    //wgpuQueueSetLabel__sig: 'vp(string view)',
    wgpuQueueSubmit__sig: 'vppp',
    wgpuQueueWriteBuffer__sig: 'vppjpp',
    wgpuQueueWriteTexture__sig: 'vpppppp',
    wgpuQueueAddRef__sig: 'vp',
    wgpuQueueRelease__sig: 'vp',
    //wgpuRenderBundleSetLabel__sig: 'vp(string view)',
    wgpuRenderBundleAddRef__sig: 'vp',
    wgpuRenderBundleRelease__sig: 'vp',
    wgpuRenderPipelineGetBindGroupLayout__sig: 'ppi',
    //wgpuRenderPipelineSetLabel__sig: 'vp(string view)',
    wgpuRenderPipelineAddRef__sig: 'vp',
    wgpuRenderPipelineRelease__sig: 'vp',
    //wgpuSamplerSetLabel__sig: 'vp(string view)',
    wgpuSamplerAddRef__sig: 'vp',
    wgpuSamplerRelease__sig: 'vp',
    //wgpuShaderModuleGetCompilationInfo__sig: '(future)p(compilation info callback info)',
    //wgpuShaderModuleSetLabel__sig: 'vp(string view)',
    wgpuShaderModuleAddRef__sig: 'vp',
    wgpuShaderModuleRelease__sig: 'vp',
    wgpuSurfaceConfigure__sig: 'vpp',
    wgpuSurfaceGetCapabilities__sig: 'ippp',
    wgpuSurfaceGetCurrentTexture__sig: 'vpp',
    wgpuSurfacePresent__sig: 'ip',
    //wgpuSurfaceSetLabel__sig: 'vp(string view)',
    wgpuSurfaceUnconfigure__sig: 'vp',
    wgpuSurfaceAddRef__sig: 'vp',
    wgpuSurfaceRelease__sig: 'vp',
    wgpuTextureCreateView__sig: 'ppp',
    wgpuTextureDestroy__sig: 'vp',
    wgpuTextureGetDepthOrArrayLayers__sig: 'ip',
    wgpuTextureGetDimension__sig: 'ip',
    wgpuTextureGetFormat__sig: 'ip',
    wgpuTextureGetHeight__sig: 'ip',
    wgpuTextureGetMipLevelCount__sig: 'ip',
    wgpuTextureGetSampleCount__sig: 'ip',
    wgpuTextureGetTextureBindingViewDimension__sig: 'ip',
    wgpuTextureGetUsage__sig: 'jp',
    wgpuTextureGetWidth__sig: 'ip',
    //wgpuTextureSetLabel__sig: 'vp(string view)',
    wgpuTextureAddRef__sig: 'vp',
    wgpuTextureRelease__sig: 'vp',
    //wgpuTextureViewSetLabel__sig: 'vp(string view)',
    wgpuTextureViewAddRef__sig: 'vp',
    wgpuTextureViewRelease__sig: 'vp',
    wgpuComputePassEncoderDispatchWorkgroups__sig: 'vpiii',
    wgpuComputePassEncoderDispatchWorkgroupsIndirect__sig: 'vppj',
    wgpuComputePassEncoderEnd__sig: 'vp',
    //wgpuComputePassEncoderInsertDebugMarker__sig: 'vp(string view)',
    wgpuComputePassEncoderPopDebugGroup__sig: 'vp',
    //wgpuComputePassEncoderPushDebugGroup__sig: 'vp(string view)',
    wgpuComputePassEncoderSetBindGroup__sig: 'vpippp',
    wgpuComputePassEncoderSetImmediates__sig: 'vpipp',
    //wgpuComputePassEncoderSetLabel__sig: 'vp(string view)',
    wgpuComputePassEncoderSetPipeline__sig: 'vpp',
    wgpuComputePassEncoderWriteTimestamp__sig: 'vppi',
    wgpuComputePassEncoderAddRef__sig: 'vp',
    wgpuComputePassEncoderRelease__sig: 'vp',
    wgpuRenderBundleEncoderDraw__sig: 'vpiiii',
    wgpuRenderBundleEncoderDrawIndexed__sig: 'vpiiiii',
    wgpuRenderBundleEncoderDrawIndexedIndirect__sig: 'vppj',
    wgpuRenderBundleEncoderDrawIndirect__sig: 'vppj',
    wgpuRenderBundleEncoderFinish__sig: 'ppp',
    //wgpuRenderBundleEncoderInsertDebugMarker__sig: 'vp(string view)',
    wgpuRenderBundleEncoderPopDebugGroup__sig: 'vp',
    //wgpuRenderBundleEncoderPushDebugGroup__sig: 'vp(string view)',
    wgpuRenderBundleEncoderSetBindGroup__sig: 'vpippp',
    wgpuRenderBundleEncoderSetImmediates__sig: 'vpipp',
    wgpuRenderBundleEncoderSetIndexBuffer__sig: 'vppijj',
    //wgpuRenderBundleEncoderSetLabel__sig: 'vp(string view)',
    wgpuRenderBundleEncoderSetPipeline__sig: 'vpp',
    wgpuRenderBundleEncoderSetVertexBuffer__sig: 'vpipjj',
    wgpuRenderBundleEncoderAddRef__sig: 'vp',
    wgpuRenderBundleEncoderRelease__sig: 'vp',
    wgpuRenderPassEncoderBeginOcclusionQuery__sig: 'vpi',
    wgpuRenderPassEncoderDraw__sig: 'vpiiii',
    wgpuRenderPassEncoderDrawIndexed__sig: 'vpiiiii',
    wgpuRenderPassEncoderDrawIndexedIndirect__sig: 'vppj',
    wgpuRenderPassEncoderDrawIndirect__sig: 'vppj',
    wgpuRenderPassEncoderEnd__sig: 'vp',
    wgpuRenderPassEncoderEndOcclusionQuery__sig: 'vp',
    wgpuRenderPassEncoderExecuteBundles__sig: 'vppp',
    //wgpuRenderPassEncoderInsertDebugMarker__sig: 'vp(string view)',
    wgpuRenderPassEncoderMultiDrawIndexedIndirect__sig: 'vppjipj',
    wgpuRenderPassEncoderMultiDrawIndirect__sig: 'vppjipj',
    wgpuRenderPassEncoderPopDebugGroup__sig: 'vp',
    //wgpuRenderPassEncoderPushDebugGroup__sig: 'vp(string view)',
    wgpuRenderPassEncoderSetBindGroup__sig: 'vpippp',
    wgpuRenderPassEncoderSetBlendConstant__sig: 'vpp',
    wgpuRenderPassEncoderSetImmediates__sig: 'vpipp',
    wgpuRenderPassEncoderSetIndexBuffer__sig: 'vppijj',
    //wgpuRenderPassEncoderSetLabel__sig: 'vp(string view)',
    wgpuRenderPassEncoderSetPipeline__sig: 'vpp',
    wgpuRenderPassEncoderSetScissorRect__sig: 'vpiiii',
    wgpuRenderPassEncoderSetStencilReference__sig: 'vpi',
    wgpuRenderPassEncoderSetVertexBuffer__sig: 'vpipjj',
    wgpuRenderPassEncoderSetViewport__sig: 'vpffffff',
    wgpuRenderPassEncoderWriteTimestamp__sig: 'vppi',
    wgpuRenderPassEncoderAddRef__sig: 'vp',
    wgpuRenderPassEncoderRelease__sig: 'vp',
};

// Delete all of the WebGPU sig info from Emscripten's builtins first.
for (const k of Object.keys(LibraryManager.library)) {
    if (k.endsWith('__sig') && (k.startsWith('emscripten_webgpu_') || k.startsWith('wgpu'))) {
        delete LibraryManager.library[k];
    }
}
mergeInto(LibraryManager.library, webgpuSigs, {allowMissing: true});
