/*
Copyright (c) 2026, Lars Brubaker
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

using System;
using System.IO;
using System.Threading.Tasks;
using MatterHackers.Agg.Image;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;

namespace MatterHackers.Agg.Tests.GoldenImages
{
	/// <summary>
	/// Byte-exact comparison of agg-sharp software renders against goldens produced by the original
	/// C++ AGG (tools/cpp-renderer, regenerated by scripts/regen-agg-reference.sh).
	/// </summary>
	/// <remarks>
	/// A golden is <c>TestData/AggReference/&lt;name&gt;.raw</c>: u32 LE width, u32 LE height, then
	/// width*height RGBA pixels, one rendering_buffer row after another. The C++ renderer attaches its
	/// buffer with a positive stride, so raw row <c>r</c> holds AGG's y = <c>r</c> - which is also
	/// agg-sharp's <see cref="ImageBuffer"/> y = <c>r</c>. No flip is applied on either side; for a demo
	/// that ran with flip_y = true that means row 0 is the bottom of what the C++ window showed.
	/// <para>
	/// There is no tolerance. These goldens are the definition of correct for the AGG demos, and the
	/// C++ renderer is deterministic, so any difference is an agg-sharp divergence to fix.
	/// </para>
	/// </remarks>
	public static class AggReference
	{
		private const string ReferenceFolderName = "AggReference";

		/// <summary>
		/// Loads the golden <paramref name="name"/> (file name without .raw) as a 32-bit BGRA image whose
		/// y = the raw row index.
		/// </summary>
		public static ImageBuffer Load(string name)
		{
			string path = Path.Combine(ReferenceDirectory(), name + ".raw");
			byte[] bytes = File.ReadAllBytes(path);
			int width = (int)BitConverter.ToUInt32(bytes, 0);
			int height = (int)BitConverter.ToUInt32(bytes, 4);
			if (bytes.Length != 8 + (width * height * 4))
			{
				throw new InvalidDataException($"'{path}' is {bytes.Length} bytes; a {width}x{height} .raw is {8 + (width * height * 4)}.");
			}

			var image = new ImageBuffer(width, height, 32, new BlenderBGRA());
			byte[] buffer = image.GetBuffer();
			for (int y = 0; y < height; y++)
			{
				int source = 8 + (y * width * 4);
				int destination = image.GetBufferOffsetY(y);
				for (int x = 0; x < width; x++)
				{
					int s = source + (x * 4);
					int d = destination + (x * 4);
					buffer[d + ImageBuffer.OrderR] = bytes[s + 0];
					buffer[d + ImageBuffer.OrderG] = bytes[s + 1];
					buffer[d + ImageBuffer.OrderB] = bytes[s + 2];
					buffer[d + ImageBuffer.OrderA] = bytes[s + 3];
				}
			}

			image.MarkImageChanged();
			return image;
		}

		/// <summary>The byte-level outcome of comparing a render against a golden.</summary>
		public readonly struct Result
		{
			public Result(int width, int height, long differingPixels, int maxChannelDelta, int firstX, int firstY, Color expected, Color actual)
			{
				Width = width;
				Height = height;
				DifferingPixels = differingPixels;
				MaxChannelDelta = maxChannelDelta;
				FirstX = firstX;
				FirstY = firstY;
				FirstExpected = expected;
				FirstActual = actual;
			}

			public int Width { get; }

			public int Height { get; }

			public long DifferingPixels { get; }

			public int MaxChannelDelta { get; }

			/// <summary>The first differing pixel in row-major order from y = 0; -1 when identical.</summary>
			public int FirstX { get; }

			public int FirstY { get; }

			public Color FirstExpected { get; }

			public Color FirstActual { get; }

			public bool Identical => DifferingPixels == 0;

			public string Describe()
			{
				if (Identical)
				{
					return "identical";
				}

				return $"{DifferingPixels} of {(long)Width * Height} pixels differ"
					+ $" ({DifferingPixels * 100.0 / ((long)Width * Height):0.####}%), largest channel delta {MaxChannelDelta},"
					+ $" first at ({FirstX}, {FirstY}): expected {Rgba(FirstExpected)}, got {Rgba(FirstActual)}.";
			}

			private static string Rgba(Color c) => $"rgba({c.red}, {c.green}, {c.blue}, {c.alpha})";
		}

		/// <summary>
		/// Compares every channel of every pixel. <paramref name="rendered"/> may be any agg-sharp pixel
		/// format - pixels are read through its blender, so BGR24 and BGRA32 renders compare the same way.
		/// A 24-bit render has no alpha channel and reads back as opaque, as C++'s pixfmt_bgr24 does.
		/// </summary>
		public static Result Compare(ImageBuffer golden, ImageBuffer rendered)
		{
			if (golden.Width != rendered.Width || golden.Height != rendered.Height)
			{
				throw new ArgumentException($"golden is {golden.Width}x{golden.Height}, render is {rendered.Width}x{rendered.Height}.");
			}

			long differing = 0;
			int maxDelta = 0;
			int firstX = -1, firstY = -1;
			Color firstExpected = default, firstActual = default;
			for (int y = 0; y < golden.Height; y++)
			{
				for (int x = 0; x < golden.Width; x++)
				{
					Color expected = golden.GetPixel(x, y);
					Color actual = rendered.GetPixel(x, y);
					int delta = Math.Max(
						Math.Max(Math.Abs(expected.red - actual.red), Math.Abs(expected.green - actual.green)),
						Math.Max(Math.Abs(expected.blue - actual.blue), Math.Abs(expected.alpha - actual.alpha)));
					if (delta == 0)
					{
						continue;
					}

					if (differing == 0)
					{
						firstX = x;
						firstY = y;
						firstExpected = expected;
						firstActual = actual;
					}

					differing++;
					maxDelta = Math.Max(maxDelta, delta);
				}
			}

			return new Result(golden.Width, golden.Height, differing, maxDelta, firstX, firstY, firstExpected, firstActual);
		}

		/// <summary>
		/// Asserts <paramref name="rendered"/> is byte-identical to the golden <paramref name="name"/>. On a
		/// mismatch the render, the golden and a diff (golden washed gray, differing pixels magenta) are
		/// written as PNGs to <c>bin/GoldenImageFailures/AggReference</c> and named in the failure.
		/// </summary>
		public static async Task Check(ImageBuffer rendered, string name)
		{
			ImageBuffer golden = Load(name);
			if (golden.Width != rendered.Width || golden.Height != rendered.Height)
			{
				string sizePath = WriteArtifact(ToBgra32(rendered), name, "actual");
				await Assert.That($"{rendered.Width}x{rendered.Height}").IsEqualTo($"{golden.Width}x{golden.Height}")
					.Because($"the render of '{name}' must be the golden's size. Rendered: '{sizePath}'.");
				return;
			}

			Result result = Compare(golden, rendered);
			if (!result.Identical)
			{
				ImageBuffer renderedBgra = ToBgra32(rendered);
				string actualPath = WriteArtifact(renderedBgra, name, "actual");
				string expectedPath = WriteArtifact(golden, name, "expected");
				string diffPath = WriteArtifact(GoldenImage.BuildDiffImage(golden, renderedBgra, 0), name, "diff");
				await Assert.That(result.Identical).IsTrue().Because(
					$"'{name}' is not byte-identical to C++ AGG: {result.Describe()}"
					+ $" Rendered: '{actualPath}'. Expected: '{expectedPath}'. Diff: '{diffPath}'.");
				return;
			}

			foreach (string suffix in new[] { "actual", "expected", "diff" })
			{
				string stale = ArtifactPath(name, suffix);
				if (File.Exists(stale))
				{
					File.Delete(stale);
				}
			}
		}

		/// <summary>
		/// Finds <c>TestData/AggReference</c> (beside ControlImages and GoldenImages) in the source tree,
		/// falling back to the copy beside the binary only when there is no tree - the same tree-first rule
		/// as <see cref="GoldenImage"/>.
		/// </summary>
		public static string ReferenceDirectory()
		{
			string probe = AppContext.BaseDirectory;
			for (int up = 0; up < 8 && probe != null; up++)
			{
				string candidate = Path.Combine(probe, "TestData", ReferenceFolderName);
				if (Directory.Exists(candidate))
				{
					return candidate;
				}

				probe = Path.GetDirectoryName(probe.TrimEnd(Path.DirectorySeparatorChar));
			}

			return Path.Combine(AppContext.BaseDirectory, ReferenceFolderName);
		}

		/// <summary>
		/// Returns <paramref name="source"/> as a 32-bit BGRA image, copying it through its own blender when
		/// it is anything else. <see cref="GoldenImage.BuildDiffImage"/> and the PNG writer both index raw
		/// bytes as BGRA, so an RGBA or BGR24 render passed straight through would come out channel-swapped
		/// or misaligned.
		/// </summary>
		private static ImageBuffer ToBgra32(ImageBuffer source)
		{
			if (source.BitDepth == 32 && source.GetRecieveBlender() is BlenderBGRA)
			{
				return source;
			}

			var copy = new ImageBuffer(source.Width, source.Height, 32, new BlenderBGRA());
			for (int y = 0; y < source.Height; y++)
			{
				for (int x = 0; x < source.Width; x++)
				{
					copy.SetPixel(x, y, source.GetPixel(x, y));
				}
			}

			return copy;
		}

		private static string ArtifactPath(string name, string suffix)
			=> Path.Combine(AppContext.BaseDirectory, "GoldenImageFailures", ReferenceFolderName, $"{name}.{suffix}.png");

		private static string WriteArtifact(ImageBuffer image, string name, string suffix)
		{
			string path = ArtifactPath(name, suffix);
			Directory.CreateDirectory(Path.GetDirectoryName(path));

			// SaveImageData reports failure by returning false; a failure message naming a file that was
			// never written would send whoever reads it looking for an image that does not exist.
			return ImageIO.SaveImageData(path, image) ? path : $"(could not write '{path}')";
		}
	}
}
